version: "3.7"
services:

  redis:
    image: redis:latest
    container_name: redis_app
    command: --port ${REDIS_PORT}
    env_file:
      ".env"
    expose:
      - ${REDIS_PORT}

  app:
    container_name: fastapi_app
    build:
      context: .
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 9999:8000
    depends_on:
      - redis

  celery:
    build:
      context: .
    container_name: celery_app
    command: celery -A app.core.celery_app:celery_app worker --loglevel=INFO  
    depends_on:
      - redis

  flower:
    build:
      context: .

    container_name: flower_app
    command: celery --app=app.core.celery_app:celery_app flower
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555